FROM arm64v8/ruby:3.1.2

RUN mkdir /app
WORKDIR /app

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends build-essential libpq-dev

COPY ./Gemfile .
COPY ./Gemfile.lock .
RUN bundle install

COPY ./scripts/entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
COPY ./ .

ENTRYPOINT ["entrypoint.sh"]

EXPOSE 3000

CMD ["rails", "s"]