
version: '3'
services:
  db:
    image: postgres
    expose:
      - 5432
    ports:
      - 5433:5432
    volumes:
      - /Users/pjacobs/docker/volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: gaspar
      POSTGRES_USER: gaspar
      POSTGRES_PASSWORD: hJ6D9pAak45!Dw7
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db